version: 2
updates:
  # Check Astro package.json
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5

  # Check CDK package.json
  - package-ecosystem: 'npm'
    directory: '/cdk'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5

  # Check Github Actions workflows
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
